apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-prod
  template:
    metadata:
      labels:
        app: hello-prod
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: hello-prod
          image: beenotice.azurecr.io/hello-prod
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-prod