spring:
  application:
      name: hello-prod
  profiles:
    active: local, prod


server:
  servlet:
    session:
      cookie:
        http-only: true

management:
  endpoints:
    web:
      exposure:
        include: '*'