spring:
  application:
    name: hello-prod
  profiles:
    # Last wins : local, prod
    active: local
  # https://docs.spring.io/spring-boot/docs/2.4.5/reference/htmlsingle/#boot-features-security
  security:
    # In memory user - TODO Change this strategy !
    user:
      name: admin
      password: f505db0a-9d14-4181-9288-3d0838be17e9
      roles: ADMIN

# https://docs.spring.io/spring-boot/docs/2.4.5/reference/htmlsingle/#common-application-properties
server:
  servlet:
    session:
      cookie:
        # Whether to use "HttpOnly" cookies for session cookies => No Js access
        http-only: true

info:
  app:
    # Reuse declared variable
    name: ${spring.application.name}
    # Retrieve data from pom.xml
    version: "@project.version@"

management:
  endpoint:
    health:
      # Required role to access endpoints
      roles: ROLE_ADMIN
      # Details are only shown to authorized users
      show-details: when-authorized
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
