# https://github.com/actions/starter-workflows/blob/main/ci/azure.yml
# https://docs.microsoft.com/fr-fr/azure/app-service/deploy-container-github-action?tabs=service-principal#deploy-to-an-app-service-container
name: Deploy hello-prod

# Run this workflow every time a new commit pushed to your repository
on: [push]


env:
  AZURE_WEBAPP_NAME: azapp-hello-app-dev
  JAVA_VERSION: 11

jobs:
  
  # Set the job key. The key is displayed as the job name when a job name is not provided
  hello-prod:

    # Used to retrieve the secret
    environment: dev
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Build with Maven
        run: mvn -B package

      - name: Login via Azure CLI
        uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: target/*.jar
          # publish-profile
          # startup-command
          # publish-profile

      - name: Azure logout
        run: |
          az logout